# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]

##Buttons
set_property PACKAGE_PIN U18 [get_ports btn]						
	set_property IOSTANDARD LVCMOS33 [get_ports btn]
# Switches
set_property PACKAGE_PIN V17 [get_ports {rst}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rst}]	
	# LEDs
#set_property PACKAGE_PIN U16 [get_ports {rst}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
set_property PACKAGE_PIN E19 [get_ports {LED}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED}]
set_property PACKAGE_PIN U19 [get_ports {LED1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED1}]
#set_property PACKAGE_PIN V19 [get_ports {rd_pulse}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {rd}]
set_property PACKAGE_PIN W18 [get_ports {empty}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {empty}]
set_property PACKAGE_PIN U15 [get_ports {full}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {full}]
#set_property PACKAGE_PIN U14 [get_ports {LED[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
#set_property PACKAGE_PIN V14 [get_ports {LED[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property PACKAGE_PIN V13 [get_ports {d_out[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[0]}]
set_property PACKAGE_PIN V3 [get_ports {d_out[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[1]}]
set_property PACKAGE_PIN W3 [get_ports {d_out[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[2]}]
set_property PACKAGE_PIN U3 [get_ports {d_out[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[3]}]
set_property PACKAGE_PIN P3 [get_ports {d_out[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[4]}]
set_property PACKAGE_PIN N3 [get_ports {d_out[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[5]}]
set_property PACKAGE_PIN P1 [get_ports {d_out[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[6]}]
set_property PACKAGE_PIN L1 [get_ports {d_out[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d_out[7]}]

	
	#7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]


set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
	
	##USB-RS232 Interface
#set_property PACKAGE_PIN B18 [get_ports rx]
#set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN B18 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]


